import{initializeApp}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,updateProfile}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";import{getFirestore,collection,addDoc,setDoc,doc,getDoc,query,where,serverTimestamp,updateDoc,onSnapshot}from"https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
const cfg={apiKey:"apiKey:"AIzaSyAmJ_fu33l0mcnezipFXAai3paGZLM5TFM",authDomain:"impacto-obu-system.firebaseapp.com",projectId:"impacto-obu-system",storageBucket:"impacto-obu-system.firebasestorage.app",messagingSenderId:"213609724304",appId:"1:213609724304:web:e68f7883294bd6cffedb15"};const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),academyId="impacto-obu",$=id=>document.getElementById(id),state={students:[],attendance:[],scanner:null};
function toast(m){const e=$("toast");e.textContent=m;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2500)}function yen(v=0){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(v)}function day(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
async function profile(u){const r=doc(db,"users",u.uid),s=await getDoc(r);if(!s.exists())await setDoc(r,{academyId,name:u.displayName||"Administrador",email:u.email,role:"admin",active:true,createdAt:serverTimestamp()})}
onAuthStateChanged(auth,async u=>{$("auth").hidden=!!u;$("app").hidden=!u;if(u){$("user").textContent=u.displayName||u.email;await profile(u);subscribe()}});$("showRegister").onclick=()=>$("register").hidden=!$("register").hidden;$("login").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("email").value,$("password").value)}catch(x){toast("Não foi possível entrar")}};$("register").onsubmit=async e=>{e.preventDefault();try{const c=await createUserWithEmailAndPassword(auth,$("regEmail").value,$("regPassword").value);await updateProfile(c.user,{displayName:$("name").value});await profile(c.user);toast("Administrador criado") }catch(x){toast("Erro ao criar conta")}};$("logout").onclick=()=>signOut(auth);
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.page));document.querySelectorAll("nav button").forEach(n=>n.classList.toggle("active",n===b))});$("newStudent").onclick=()=>$("studentDialog").showModal();$("closeDialog").onclick=()=>$("studentDialog").close();
$("studentForm").onsubmit=async e=>{e.preventDefault();const code=`OBU-${Date.now().toString().slice(-7)}`;try{await addDoc(collection(db,"students"),{academyId,registrationNumber:code,fullName:$("studentName").value.trim(),category:$("category").value,belt:$("belt").value,monthlyFee:Number($("fee").value||0),dueDay:10,responsibleName:$("responsible").value.trim(),phone:$("phone").value.trim(),active:true,paidCurrentMonth:false,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});$("studentDialog").close();$("studentForm").reset();$("fee").value=8800;toast(`Aluno salvo. QR: ${code}`)}catch(x){toast("Erro ao salvar")}};
function subscribe(){onSnapshot(query(collection(db,"students"),where("academyId","==",academyId)),s=>{state.students=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.fullName||"").localeCompare(b.fullName||""));render()});onSnapshot(query(collection(db,"attendance"),where("academyId","==",academyId),where("dateKey","==",day())),s=>{state.attendance=s.docs.map(d=>({id:d.id,...d.data()}));render()})}
function render(){const a=state.students.filter(s=>s.active!==false),r=a.filter(s=>s.paidCurrentMonth).reduce((n,s)=>n+(s.monthlyFee||0),0),p=a.filter(s=>!s.paidCurrentMonth).reduce((n,s)=>n+(s.monthlyFee||0),0);$("mStudents").textContent=a.length;$("mAttendance").textContent=state.attendance.length;$("mReceived").textContent=yen(r);$("mPending").textContent=yen(p);renderStudents();renderFinance();renderAttendance()}
function renderStudents(){const q=$("search").value.toLowerCase();$("studentList").innerHTML=state.students.filter(s=>(s.fullName||"").toLowerCase().includes(q)).map(s=>`<article class="row"><div><b>${s.fullName}</b><small>${s.category} • ${s.belt}<br>QR: ${s.registrationNumber}</small></div><span class="badge ${s.paidCurrentMonth?"paid":"pending"}">${s.paidCurrentMonth?"Pago":"Pendente"}</span></article>`).join("")||"<p>Nenhum aluno.</p>"}$("search").oninput=renderStudents;
function renderFinance(){$("financeList").innerHTML=state.students.map(s=>`<article class="row"><div><b>${s.fullName}</b><small>${yen(s.monthlyFee)} • dia ${s.dueDay||10}</small></div><button class="badge ${s.paidCurrentMonth?"paid":"pending"}" data-id="${s.id}">${s.paidCurrentMonth?"Pago":"Marcar pago"}</button></article>`).join("");document.querySelectorAll("#financeList button").forEach(b=>b.onclick=async()=>{const s=state.students.find(x=>x.id===b.dataset.id);await updateDoc(doc(db,"students",s.id),{paidCurrentMonth:!s.paidCurrentMonth,paymentUpdatedAt:serverTimestamp()})})}
function renderAttendance(){$("attendanceList").innerHTML=state.attendance.map(a=>`<article class="row"><div><b>${a.studentName}</b><small>${a.method}</small></div><span class="badge paid">Presente</span></article>`).join("")||"<p>Nenhuma presença hoje.</p>"}
async function checkin(code,method="qr"){const c=(code||"").trim().toUpperCase(),s=state.students.find(x=>(x.registrationNumber||"").toUpperCase()===c);if(!s)return toast("QR não encontrado");if(state.attendance.some(a=>a.studentId===s.id))return toast("Presença já registrada");await addDoc(collection(db,"attendance"),{academyId,studentId:s.id,studentName:s.fullName,registrationNumber:s.registrationNumber,dateKey:day(),method,checkedInAt:serverTimestamp(),registeredBy:auth.currentUser.uid});toast(`Presença: ${s.fullName}`)}$("manualBtn").onclick=()=>{checkin($("manualCode").value,"manual");$("manualCode").value=""};$("startScan").onclick=async()=>{try{state.scanner=new Html5Qrcode("reader");await state.scanner.start({facingMode:"environment"},{fps:10,qrbox:230},t=>checkin(t,"qr"),()=>{});$("startScan").hidden=true;$("stopScan").hidden=false}catch(x){toast("Não foi possível abrir a câmera")}};$("stopScan").onclick=async()=>{if(state.scanner){await state.scanner.stop();state.scanner.clear();state.scanner=null}$("startScan").hidden=false;$("stopScan").hidden=true};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
